In [1]:
#including libraries 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
#uploading csv 
df=pd.read_csv('croplocation.csv')

In [3]:
#performing some data exploration steps
df.head()

Latitude and Longitude Class of Land
0   (10.323727047081501, 105.2516346045924)          Rice
1  (10.322364360592521, 105.27843410554115)          Rice
2  (10.321455902933202, 105.25254306225168)          Rice
3  (10.324181275911162, 105.25118037576274)          Rice
4  (10.324635504740822, 105.27389181724476)          Rice

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Latitude and Longitude  600 non-null    object
 1   Class of Land           600 non-null    object
dtypes: object(2)
memory usage: 9.5+ KB


In [5]:
df.describe()

Latitude and Longitude Class of Land
count                                       600           600
unique                                      600             2
top     (10.323727047081501, 105.2516346045924)          Rice
freq                                          1           300

In [6]:
#from pandas_profiling import ProfileReport
##profile.to_widgets()

In [7]:
#observation
# As observation given by pandas profling report some of the observations are-:
#1.We have latitude and logitude as a tuple and we cannnot work on that
#2.Data has total 600 observations
#3.No duplicate rows and 0 missing cells
#4. Two categorical values

In [8]:
# making two new feature column named latitude and Longitude because we cannot work upon tuple
# so i splitted the tuple using .split on the basis of ','
df[['Latitude', 'Longitude']] = df['Latitude and Longitude'].str.split(',', expand=True)



In [9]:
# no need of latitude and longitude so i dropped it
df.drop('Latitude and Longitude', axis=1, inplace=True)

In [10]:
# again viewing the data still it has paranthesis in it 
df.head()

Class of Land             Latitude             Longitude
0          Rice  (10.323727047081501    105.2516346045924)
1          Rice  (10.322364360592521   105.27843410554115)
2          Rice  (10.321455902933202   105.25254306225168)
3          Rice  (10.324181275911162   105.25118037576274)
4          Rice  (10.324635504740822   105.27389181724476)

In [11]:
# removing parenthesis using strip and converting it into float values
df['Latitude'] = df['Latitude'].apply(lambda x: float(x.strip('()')))
df['Longitude'] = df['Longitude'].apply(lambda x: float(x.strip('()')))

print(df)

    Class of Land   Latitude   Longitude
0            Rice  10.323727  105.251635
1            Rice  10.322364  105.278434
2            Rice  10.321456  105.252543
3            Rice  10.324181  105.251180
4            Rice  10.324636  105.273892
..            ...        ...         ...
595      Non Rice  10.013943  105.673613
596      Non Rice  10.013489  105.673613
597      Non Rice  10.013035  105.673613
598      Non Rice  10.012580  105.673613
599      Non Rice  10.012126  105.673613

[600 rows x 3 columns]


In [12]:
# converting categorical variables rice and non-rice into numerical variable 0 and 1 using map 
mape={'Rice':1,'Non Rice':0}
df['Class of Land']=df['Class of Land'].map(mape)

In [13]:
print(df)

     Class of Land   Latitude   Longitude
0                1  10.323727  105.251635
1                1  10.322364  105.278434
2                1  10.321456  105.252543
3                1  10.324181  105.251180
4                1  10.324636  105.273892
..             ...        ...         ...
595              0  10.013943  105.673613
596              0  10.013489  105.673613
597              0  10.013035  105.673613
598              0  10.012580  105.673613
599              0  10.012126  105.673613

[600 rows x 3 columns]


In [14]:
# setting independent varibales in x and dependent variables in y
X=df.drop('Class of Land',1)
y=df['Class of Land']


C:\Users\singh\AppData\Local\Temp\ipykernel_14192\1380795605.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X=df.drop('Class of Land',1)


In [15]:
X

Latitude   Longitude
0    10.323727  105.251635
1    10.322364  105.278434
2    10.321456  105.252543
3    10.324181  105.251180
4    10.324636  105.273892
..         ...         ...
595  10.013943  105.673613
596  10.013489  105.673613
597  10.013035  105.673613
598  10.012580  105.673613
599  10.012126  105.673613

[600 rows x 2 columns]

In [16]:
y

0      1
1      1
2      1
3      1
4      1
      ..
595    0
596    0
597    0
598    0
599    0
Name: Class of Land, Length: 600, dtype: int64

In [17]:
# using random forest classifier  and train test split for decision making
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [18]:
# dividing data into training data and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [19]:
# making object for randomforestclassifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)

In [20]:
#fitting the data
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [21]:
#doing prediction and finding accuracy score
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")


Accuracy: 1.0


In [22]:
# observations are accuracy score is 1.0 which is sign of success


In [23]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix

In [24]:
confusion_matrix(y_true=y_test,y_pred=y_pred)

array([[58,  0],
       [ 0, 62]], dtype=int64)

In [25]:
df2=pd.read_csv('challenge_1_submission_template_correct_columns_fixed (2).csv')

In [26]:
df2.head()

id  target
0   (10.18019073690894, 105.32022315786804)     NaN
1  (10.561107033461816, 105.12772097986661)     NaN
2  (10.623790611954897, 105.13771401411867)     NaN
3  (10.583364246115156, 105.23946127195805)     NaN
4   (10.20744446668854, 105.26844107128906)     NaN

In [27]:
df2['id']

0       (10.18019073690894, 105.32022315786804)
1      (10.561107033461816, 105.12772097986661)
2      (10.623790611954897, 105.13771401411867)
3      (10.583364246115156, 105.23946127195805)
4       (10.20744446668854, 105.26844107128906)
                         ...                   
245    (10.308283266873062, 105.50872812216863)
246    (10.582910017285496, 105.23991550078767)
247    (10.581547330796518, 105.23991550078767)
248    (10.629241357910818, 105.15315779432643)
249    (10.574733898351617, 105.10410108072531)
Name: id, Length: 250, dtype: object

In [28]:
df2[['Latitude', 'Longitude']] = df2['id'].str.split(',', expand=True)


In [29]:
df2.drop('id', axis=1, inplace=True)

In [30]:
df2['Latitude'] = df2['Latitude'].apply(lambda x: float(x.strip('()')))
df2['Longitude'] = df2['Longitude'].apply(lambda x: float(x.strip('()')))


In [31]:
df2

target   Latitude   Longitude
0       NaN  10.180191  105.320223
1       NaN  10.561107  105.127721
2       NaN  10.623791  105.137714
3       NaN  10.583364  105.239461
4       NaN  10.207444  105.268441
..      ...        ...         ...
245     NaN  10.308283  105.508728
246     NaN  10.582910  105.239916
247     NaN  10.581547  105.239916
248     NaN  10.629241  105.153158
249     NaN  10.574734  105.104101

[250 rows x 3 columns]

In [32]:
y2=df2.drop('target',1)

C:\Users\singh\AppData\Local\Temp\ipykernel_14192\582817177.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  y2=df2.drop('target',1)


In [33]:
y2

Latitude   Longitude
0    10.180191  105.320223
1    10.561107  105.127721
2    10.623791  105.137714
3    10.583364  105.239461
4    10.207444  105.268441
..         ...         ...
245  10.308283  105.508728
246  10.582910  105.239916
247  10.581547  105.239916
248  10.629241  105.153158
249  10.574734  105.104101

[250 rows x 2 columns]

In [34]:
y3=clf.predict(y2)

In [35]:
y3

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [36]:
n_ans=np.array(y3)

In [37]:
n_ans

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [38]:
df3=pd.read_csv('challenge_1_submission_template_correct_columns_fixed (2).csv')

In [39]:
df3['target']=n_ans

In [40]:
df3.to_csv('df3.csv',index=False)

In [41]:
mape={0:'Non Rice',1:'Rice'}
df3['target']=df3['target'].map(mape)

In [42]:
df3

id    target
0     (10.18019073690894, 105.32022315786804)      Rice
1    (10.561107033461816, 105.12772097986661)  Non Rice
2    (10.623790611954897, 105.13771401411867)  Non Rice
3    (10.583364246115156, 105.23946127195805)  Non Rice
4     (10.20744446668854, 105.26844107128906)      Rice
..                                        ...       ...
245  (10.308283266873062, 105.50872812216863)  Non Rice
246  (10.582910017285496, 105.23991550078767)  Non Rice
247  (10.581547330796518, 105.23991550078767)  Non Rice
248  (10.629241357910818, 105.15315779432643)  Non Rice
249  (10.574733898351617, 105.10410108072531)  Non Rice

[250 rows x 2 columns]

In [44]:
df5=df3

In [45]:
df5.to_csv('df5.csv',index=False)